spring:
  application:
    name: 'website-selling-technology_backend'
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/website_selling_technology?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${MYSQL_ROOT_PASSWORD:Gizmos@230523}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: gizmos.services@gmail.com
    password: aiwgpldbgacwkeyd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration
    # Phiên bản baseline sẽ = 1 và không thực hiện bất kỳ thay đổi nào trong DB
    baseline-on-migrate: true
    baseline-version: 0
  redis:
    host: ${REDIS_HOST:localhost} # Default to 'localhost' if not provided
    port: ${REDIS_PORT:6379}      # Default to 6379 if not provided
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # transaction-id-prefix: tx
      properties:
        "[spring.json.type.mapping]": category:vn.jully.website_selling_technology_backend.entities.Category
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en

api:
  prefix: /api/v1
jwt:
  expiration: 2592000 # 30 days = 30 * 24 * 60 * 60
  expiration-refresh-token: 5184000 #60 days = 60 * 24 * 60 * 60
  secretKey: QKtxW32nmnY/2anIVO3gKjkmYBnG8KE+5sOCiaubtLY=

payment:
  vnPay:
    url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
    tmnCode: S01X4W3L
    secretKey: 6KYR7JXW0RVE4ZMQ51FVE5YO8E8NSCYJ
    returnUrl: http://localhost:8080/api/v1/payments/vn-pay-callback
    version: 2.1.0
    command: pay
    orderType: other

logging:
  level:
    org:
      springframework.security: DEBUG

#swaffer-ui custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

# heath check
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /api/v1/actuator
      exposure:
        # include: "health"
        include: "health, info"