spring:
  application:
    name: 'website-selling-technology_backend'
  datasource:
    url: 'jdbc:mysql://localhost:3306/website_selling_technology'
    username: root
    password:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    hibernate:
      ddl-auto: none
api:
  prefix: api/v1