spring:
  application:
    name: 'website-selling-technology_backend'
  datasource:
    url: 'jdbc:mysql://localhost:3306/website_selling_technology'
    username: root
    password:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: gizmos.services@gmail.com
    password: aiwgpldbgacwkeyd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  messages:
    basename: i18n/messages
    encoding: UTF-8
    default-locale: en

api:
  prefix: api/v1
jwt:
  expiration: 2592000 # 30 days = 30 * 24 * 60 * 60
  secretKey: QKtxW32nmnY/2anIVO3gKjkmYBnG8KE+5sOCiaubtLY=
